# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5d98de082e66eee75515ff4d65738fb43861204a4fa5f7564a42b9cb0f5a9b02caf8369e5ec0b2b1afc49ff72d3a9beab693cbbb9238777731a68518c34d53e

test:
  secret_key_base: 3b89ac5766cd740b2f757266fd4e26501586cd98d600b580114237ab4b14fe6b59370911f508ce52e73b6d5bc0e7636628ee0a32d840b72de7cb2f72b1a2caee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
